### PR TITLE
Add a helper class for no rounded corners

### PR DESCRIPTION
**Pull request by yianni-ververis**
Fixes #[issue number].

### Status

* [ ] Under development
* [ ] Waiting for code review
* [ ] Waiting for merge

### Information

* [ ] Contains breaking changes
* [ ] Contains new API(s)
* [ ] Contains new UI component(s)
* [ ] Contains documentation
* [ ] Contains test

### To-do list

* [ ] [Fix this thing]
* [ ] [Fix another thing]
* [ ] ...

### CODE REVIEW

**Comment by ricsv** [comment]
I suggest changing the class name to `lui-noborder` which is more consistent to the existing `lui-nopad` class. Would also be great if you could include a screenshot of how the result looks like here 🙂

**Comment by yianni-ververis** [comment]
noborder will confuse to an actual no border line. What about no-round-corner, noroundcorner, no-corner or nocorner

**Comment by yianni-ververis** [comment]
image

**Comment by ricsv** [comment]
You are right about `lui-noborder` not being the best class name. Could we use `lui-noround` instead?

**Comment by peol** [comment]
@yianni-ververis Hi! Please submit your CLA/contributors file in the https://github.com/qlik-oss/open-source repository (the signing of CLA applies to all our open-source libraries, so you only need to sign it once).

**Comment by ricsv** [comment]
Hi @yianni-ververis and sorry for the late reply!

It would be very nice to merge this PR 🙂 There are only two small things that I think need to be changed: rename the class to `lui-noround` or `lui-noradius` and remove the bump of library version in `package.json`.

**Comment by yianni-ververis** [comment]
@ricsv 
classes changed to ".lui-noround" and version to "version": "1.0.4",

**Review by ricsv — APPROVED** [review]

**Comment by ricsv** [comment]
Thanks!

Your changes are now published in version `1.1.0`.

**Pull request merged**
